//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factory()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int factory_id { get; set; }
        public string factory_name { get; set; }
        public string factory_address { get; set; }
        public string factory_phone { get; set; }
        public int factory_person_id { get; set; }
        public int factory_manager_id { get; set; }
        public int marketing_id { get; set; }
    
        public virtual FactoryManager FactoryManager { get; set; }
        public virtual FactoryPerson FactoryPerson { get; set; }
        public virtual MarketingDepartment MarketingDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
