//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int product_price { get; set; }
        public string product_category { get; set; }
        public int factory_id { get; set; }
    
        public virtual Factory Factory { get; set; }
    }
}
